# Copied into the guest verbatim by maf_sandbox._shim.host_tool_shim, which appends the caller's
# `_TIMEOUT` and one wrapper per tool. Stays annotation- and dependency-free for old guest Python.
"""Host tools, over files. Generated by maf-sandbox — editing this changes nothing host-side.

Every call is validated, gated and capped in the host process. This module's job is to write a
request where the supervisor is looking and to wait for the answer.
"""

import json
import os
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
_CALLS = os.path.join(_HERE, "host_tool_calls")
_TIMEOUT = 300.0
_POLL = 0.05


class HostToolError(RuntimeError):
    """A refusal from the host, or the host never answering. The sentence is the message."""


def _claim():
    """Take the lowest identifier no other caller holds.

    A lock would only cover this process. A program that forks, or uses `multiprocessing`,
    gets a second copy of this module with its own idea of the next number, and two copies
    counting privately write one request path: one call overwrites the other, and both
    callers read one answer as their own. `os.open` with `O_CREAT | O_EXCL` is a single
    filesystem operation that exactly one caller wins, whichever process or thread it is in.

    A file of its own rather than the request path, so allocation does not depend on the
    supervisor's rule that an empty file has not arrived yet. Claims are never removed: a
    number this hands out is published under, as a request or as an abandonment, and from the
    lowest each time because a process cannot know what the others have already taken.
    """
    number = 1
    while True:
        claim = os.path.join(_CALLS, "%04d.claim" % number)
        try:
            os.close(os.open(claim, os.O_CREAT | os.O_EXCL | os.O_WRONLY))
        except FileExistsError:
            number += 1
            continue
        return "%04d" % number


def _publish(request, payload):
    """Put `payload` at `request`, whole or not at all.

    Written aside and renamed: `open` creates the file empty, and a supervisor polling in that
    window would read no JSON and answer a call with a refusal it can never retry.
    `os.replace` is atomic on every platform this runs on.
    """
    staged = request + ".part"
    with open(staged, "w", encoding="utf-8") as handle:
        handle.write(payload)
    os.replace(staged, request)


def call(name, **arguments):
    """Call the host tool ``name`` with keyword ``arguments`` and return its value."""
    os.makedirs(_CALLS, exist_ok=True)
    identifier = _claim()
    request = os.path.join(_CALLS, identifier + ".request.json")
    try:
        _publish(request, json.dumps({"id": identifier, "name": name, "arguments": arguments}))
    except BaseException:
        # Published as abandoned rather than released. Giving the number back only helps if
        # somebody takes it, and the caller who would is often past it already: the supervisor
        # answers 0001 before it looks at 0002, so a concurrent caller that has published 0002
        # waits behind a hole that only a *third* call would fill. A marker is a hole the
        # supervisor can step over, which needs no third call and no shared lock.
        try:
            _publish(request, json.dumps({"id": identifier, "abandoned": True}))
        except Exception:
            # The filesystem is refusing writes, which is very likely why we are here at all.
            # The original failure is the one worth raising; the run is already lost.
            pass
        raise
    response = os.path.join(_CALLS, identifier + ".response.json")
    deadline = time.monotonic() + _TIMEOUT
    while time.monotonic() < deadline:
        try:
            with open(response, encoding="utf-8") as handle:
                answered = json.load(handle)
        except (OSError, ValueError):
            # Absent, or caught mid-write: the supervisor writes the whole file in one call,
            # but a backend is free to make that visible in pieces.
            time.sleep(_POLL)
            continue
        if "value" in answered:
            return answered["value"]
        raise HostToolError(answered.get("refusal", "Error: the host refused this call"))
    raise HostToolError("Error: the host did not answer this call within %g seconds" % _TIMEOUT)
