"""Install the repository's runtime-resolving Git hook wrappers."""

from __future__ import annotations

import subprocess
from pathlib import Path

HOOK_TYPES = ("pre-commit", "pre-push", "commit-msg")
HOOK_DIR_NAME = "maf-hooks"
HOOK_MARKER = "# Generated by maf-extensions; do not edit."


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _hook_script(hook_type: str) -> str:
    return f"""#!/bin/sh
{HOOK_MARKER}
# Runs the {hook_type} tier of .pre-commit-config.yaml through `uv`, resolved at run time.
set -e
root=$(git rev-parse --show-toplevel)
exec uv run --project "$root" pre-commit hook-impl \\
    --config="$root/.pre-commit-config.yaml" \\
    --hook-type={hook_type} \\
    --hook-dir "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)" -- "$@"
"""


def main() -> None:
    """Write the hook wrappers and configure their shared Git directory."""
    root = Path(_git("rev-parse", "--show-toplevel"))
    common_dir = Path(_git("-C", str(root), "rev-parse", "--git-common-dir"))
    if not common_dir.is_absolute():
        common_dir = (root / common_dir).resolve()
    hook_dir = common_dir / HOOK_DIR_NAME
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_paths = [hook_dir / hook_type for hook_type in HOOK_TYPES]
    for path in hook_paths:
        if path.exists() and HOOK_MARKER not in path.read_text(encoding="utf-8"):
            raise RuntimeError(f"Refusing to replace an existing hook: {path}")

    for hook_type, path in zip(HOOK_TYPES, hook_paths, strict=True):
        path.write_text(_hook_script(hook_type), encoding="utf-8", newline="\n")
        path.chmod(0o755)

    subprocess.run(["git", "config", "core.hooksPath", str(hook_dir)], check=True)
    print(f"Installed Git hooks in {hook_dir}")


if __name__ == "__main__":
    main()
