"""Install the repository's runtime-resolving Git hook wrappers."""

from __future__ import annotations

import subprocess
from pathlib import Path

HOOK_TYPES = ("pre-commit", "pre-push", "commit-msg")
HOOK_MARKER = "# Generated by maf-extensions; do not edit."


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _hook_script(hook_type: str) -> str:
    return f"""#!/bin/sh
{HOOK_MARKER}
set -e
root=$(git rev-parse --show-toplevel)
exec uv run --project "$root" pre-commit hook-impl \\
    --config="$root/.pre-commit-config.yaml" \\
    --hook-type={hook_type} \\
    --hook-dir "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)" -- "$@"
"""


def main() -> None:
    """Write the hook wrappers and configure their shared Git directory."""
    root = Path(_git("rev-parse", "--show-toplevel"))
    configured_path = subprocess.run(
        ["git", "config", "--get", "core.hooksPath"],
        check=False,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if configured_path:
        raise RuntimeError(
            "core.hooksPath is already configured; unset it before installing repository hooks"
        )
    hook_dir = Path(_git("-C", str(root), "rev-parse", "--git-path", "hooks"))
    if not hook_dir.is_absolute():
        hook_dir = (root / hook_dir).resolve()
    hook_dir.mkdir(parents=True, exist_ok=True)
    hook_paths = [hook_dir / hook_type for hook_type in HOOK_TYPES]
    for path in hook_paths:
        if path.is_symlink() or (
            path.exists() and HOOK_MARKER not in path.read_text(encoding="utf-8")
        ):
            raise RuntimeError(f"Refusing to replace an existing hook: {path}")

    for hook_type, path in zip(HOOK_TYPES, hook_paths, strict=True):
        path.write_text(_hook_script(hook_type), encoding="utf-8", newline="\n")
        path.chmod(0o755)

    print(f"Installed Git hooks in {hook_dir}")


if __name__ == "__main__":
    main()
