FROM cgr.dev/chainguard/wolfi-base@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03

RUN apk upgrade --no-cache && apk add --no-cache python-3.13 graphviz ttf-dejavu && dot -c

CMD ["sleep", "infinity"]
